### ISSUE TITLE
Github Pages Deployment

### ISSUE THREAD

**Issue by schnittstabil** [agda/agda-spec#2]
I try to follow the progress of this project, but I do not like to read the tex files :wink:

Are you interested in a PR, which will continuously build PDFs of your `*.tex` files, and deploy those PDFs to a `gh-pages` branch?

– I've already fiddled around with that idea at https://github.com/schnittstabil/agda-spec,
and the PR would essentially look like https://github.com/schnittstabil/agda-spec/commit/81e8542c823cd831c3f85984058a73771778124a.

**Comment by andreasabel** [comment]
Ah, yes that would be great!

**Comment by halfaya** [comment]
We could also just build PDF files ourself and check them in to github,
which leaves the possibility that the pdf file posted is out of sync with
the latest tex file but in reality we always make one after any changes.
It would be easier for people who want to read the PDF easily and we don't
have to worry about running CI which seems overkill for documentation.

John

**Comment by schnittstabil** [comment]
CI would also verify that the PDFs _can_ be build and [`.travis.yml`](https://github.com/schnittstabil/agda-spec/blob/master/.travis.yml#L5-L10) demonstrates _how_ (at least at Ubuntu):

```yml
before_install:
  - sudo apt-get -q update
  - sudo apt-get install -y texlive-latex-extra texlive-math-extra mathpartir

script:
  - make docs
```

Despite CI would continuously do a simple _syntax check_ for `.tex` files,
1. CI/Tests could also check for syntax errors of `.agda` files, e.g. by executing [`Syntax.agda`](https://github.com/agda/agda-spec/blob/master/agda/Syntax.agda)
2. CI/Tests could also verify syntax (and semantic, if you like) of examples
3. CI prevents from shipping outdated PDFs
4. CI prevents from shipping PDFs, which can be build only in environments of some people (using undocumented setup)

But that's just my two cents. I don't plan to contribute to the spec itself, so I don't know if it is worth.

**Comment by andreasabel** [comment]
I'd be happy to receive a pull request like you described.
